# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
node_js:
  - '0.10'
before_install:
  - npm install coffee-script --global

# SAUCE_TOKENS
env:
  global:
  - secure: jjtcrAH/XBngBsxfjvP2NExtTUa1CsCYqdvCfLPyb7Sj+dO6lV8mMmR2RdVGvEWuEiim7vq/R/YLKdFlkBt8kUPaZO/7xjll1Z+5U2gmxH+Tfhr3rISEFDemUCJCih1piJM60Pgkde6ybzDSU1WEt1zVmqjOR3LjoQMFYJfiZn0Ar909Cj8yO9bBvTh92llDaj47AJ9r5vllzG2duHnjHJgNAveXztuKhQLSZw5KNIvCzhSeyjMrVHp9oXY0ciBVy+8RUxqkUIqoN/K/9GIT+N0p38a9HcZEy7bYUuSsSZ4oxUC18/uzcQsinS6VD7O86KBdhX4V9xxB2+a6tfB9+H3WUPrTIWWNYDRaPqMjmvmgwa5sPFX61sqK7R5SrsmO+A0eJji6pMTi3xdl6jbUcKYk9tG5RT4t8Z+gpU1AzWG55TSCITxq/l98YDXRkqYe67++Mw9YbboIqQIKRKhQpa4J6QWm8qTsO367/pLZQJOPMUbqAFURMcQPBx5Hig7SEERsvS5lE/od+SHeGGeD5qOvElRpRVrhkhvF5PerS9jWTADbrjBuLc8HAXD1XxUCi0vRY8ZHXRzohvdItZuGHNRsk6f6EGCZLc3fkFE1QCwFBIVKa/PJA8ZTOI172X6vV8Cv+pJ/hl91YF+NMOK0VtZ6Ni7IUnDI3voulwTuRpk=
  - secure: CXT1dRaYK9mwWAZvdFpZdtR+p908DnfNLA7PHAV6ZA3KYjI3VbNitMrvJRHTnL0lT1tGlcF+n7FHMU2M/a5JlhcN2xPm4pfJxaeM6K1XvW9V13/II5nT9eEWMLIDMA+TGKfn7nBxhkyv9E9UZS4U11dgFMCmR34OzTYoTG6osrihmHzlDQ+9hYD9F3Js1FKlZLLLJYy5wp1fofz32iu/wtp7z901+ETXrHXhqFI0IIuiEbGV3H9DGNe+smn5lK96GQhT/o0ztTZH/EzlTgQ3cBILhRDurHutDCu87WV63lyhi78/6uIxsav4XksS5ZqeMIA/1Q/rJbbKKWuDtr8c+1//YUe79bghuPKIj1dSX/POLIFMPMVpQR64YAdZBQ5z9Ld60OohtXuRwmDXF7ZDqjJCaspZLwzPstoITNeJ6hfN8Yjn4mIjnRf+TV1EojhgW3+pspwrkaESIgk/WQahU1QrJvFe7n2iFTPMXSTJ+d79089avE7BkJ+BWzhKpC5Ed209jmdYdAmbPaZITpF/gMogrO9fWYWYHBCb8bcWqsj1xlaqO25mCec66nQSwMPECppSMfcfwzDsc3nGECZ/7GI+k1X4XcJCQWL6xNN2zr50Z17Nut4WsG7MEaRTBtkmaXCGGLlPBtpTiyoaIKPpTXwUzwtUQ7UvTrcpV9lhQWs=

# Npm publish options
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: W2Gyc/u7twP4pFKCpG3Sh+qBqttF+Pbfgh3StcqwYte9l7OpLXBHbCMNfeUcWKCtjEIsflZD55rXApSeA7FP2+8u/NZvvzh3Obg7od9q54chhE24qM82hcliZpHcLo+RVXDrwZUOxdqI9p4FWwuZvtmQrIB7PZPR+5fWkwarcqtWWeyXFH/4isAPB7RSaLIAt5DFaoQpgDCESp6HyLDsNF8xN+CVoLRHZMDNvPLRNp1vtq/P/wCV0JZCpxc1HG28Twgbd1woOLuDubeY/E6+7ymE5Lv8XK5NXmgdNcnsx2PWBiSuDI3fhxn3fojh0tsKeea696Rjo75qTxt5WYvdcr01Ng0dgtPk286j9gxcdXAIqZNjesC6mux3NGZXv95fYGQL1rro1nYidDv4f7D4n8rsiJxYQMN9ydw8R5TTX2Tyl4J3Bp/Mtq0RtZShAmGE/eut30teGcRdnuZDZl3XCQvOL2KilMkBvXWq+2i6pcPPQ2tDRml60Umm/61j+nUHNymWGKbP4Rgh9qqvAFZ9xDlMteeWU6BnfdNIz3f5I9fBQIchlKLUpo5OmBh9Bdu742i3wZghi+//V6naJ7kO/gkJW9dW8Ie85BaMqk+1SC9jDRpzqBBxfqkVIWCbDJZVbVPBaeJKNLz3iFbr5ycNCKbC/dIUUjgr/rwk4v0P/0s=
